# Generated by Django 4.1.2 on 2022-10-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40, verbose_name='LastName')),
                ('first_name', models.CharField(max_length=40, verbose_name='FirstName')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number', models.IntegerField(verbose_name='Phone number')),
                ('products', models.TextField(max_length=100, verbose_name='Name of products')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Date and Time')),
            ],
        ),
    ]
